kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true    # Ciliumを使うため
  kubeProxyMode: none        # Cilium kube-proxy replacement
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30082
        hostPort: 30082
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      - containerPort: 30000
        hostPort: 40000
        protocol: TCP
      - containerPort: 30001
        hostPort: 40001
        protocol: TCP
      - containerPort: 4245
        hostPort: 4245
        protocol: TCP
      - containerPort: 12001
        hostPort: 12001
        protocol: TCP
      - containerPort: 8123
        hostPort: 48123
        protocol: TCP
      - containerPort: 9000
        hostPort: 49000
        protocol: TCP
  - role: worker
  - role: worker
